"""Narrow wire contract shared by FTP, WebDAV, S3, and R2 adapters."""

from pathlib import Path
from typing import Protocol


class RemoteBackendPort(Protocol):
    """The remote file operations required by the sync service."""

    def connect(self) -> None: ...

    def ensure_remote_dir(self, path: str) -> bool | None: ...

    def upload_file(self, local_path: Path, remote_path: str) -> bool: ...

    def download_file(self, remote_path: str, local_path: Path) -> bool: ...

    def file_exists(self, path: str) -> bool: ...

    def delete_file(self, path: str) -> bool: ...

    def list_files(self, path: str) -> list[str]: ...

    def test_connection(self) -> None: ...

    def close(self) -> None: ...
